In [ ]:
import numpy as np
import pandas as pd
!pip install anndata
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

Collecting anndata
  Downloading anndata-0.12.11-py3-none-any.whl.metadata (9.9 kB)
Collecting array-api-compat>=1.7.1 (from anndata)
  Downloading array_api_compat-1.14.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata) (3.16.0)
Collecting legacy-api-wrap (from anndata)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata) (8.4.0)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.0.2)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata) (26.1)
Requirement already satisfied: pandas!=2.1.2,<3,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.2.2)
Requirement already satisfied: scipy!=1.17.0,>=1.12 in /usr/local/lib/python3.12/dist-packages (from anndata) (1.16.3)
Collecting scverse-misc>=0.0.3 (from anndata)
  Downloading scverse_misc-0.0.5-py3-none-any.whl.metadata (4.4 kB)
Collecting zarr!=3.0.*,>=2.18.7 (from anndata)
  Downloading zarr-3.1.6-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2026.1)
Collecting session-info2 (from scverse-misc>=0.0.3->anndata)
  Downloading session_info2-0.4.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from scverse-misc>=0.0.3->anndata) (4.15.0)
Collecting donfig>=0.8 (from zarr!=3.0.*,>=2.18.7->anndata)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata) (1.8.0)
Collecting numcodecs>=0.14 (from zarr!=3.0.*,>=2.18.7->anndata)
  Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.2,<3,>=2.1.0->anndata) (1.17.0)
Downloading anndata-0.12.11-py3-none-any.whl (174 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.3/174.3 kB 3.7 MB/s eta 0:00:00
Downloading array_api_compat-1.14.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 5.5 MB/s eta 0:00:00
Downloading scverse_misc-0.0.5-py3-none-any.whl (12 kB)
Downloading zarr-3.1.6-py3-none-any.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 11.0 MB/s eta 0:00:00
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 73.9 MB/s eta 0:00:00
Downloading session_info2-0.4.1-py3-none-any.whl (17 kB)
Installing collected packages: session-info2, numcodecs, legacy-api-wrap, donfig, array-api-compat, zarr, scverse-misc, anndata
Successfully installed anndata-0.12.11 array-api-compat-1.14.0 donfig-0.8.1.post1 legacy-api-wrap-1.5 numcodecs-0.16.5 scverse-misc-0.0.5 session-info2-0.4.1 zarr-3.1.6
0.12.11

/tmp/ipykernel_6674/1630374258.py:6: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(ad.__version__)

In [ ]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
adata

AnnData object with n_obs × n_vars = 100 × 2000

In [ ]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 126595 stored elements and shape (100, 2000)>

In [ ]:
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:10])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')

In [ ]:
adata[["Cell_1", "Cell_10"], ["Gene_5", "Gene_1900"]]

View of AnnData object with n_obs × n_vars = 2 × 2

In [ ]:
# Adding aligned metadata
# Observation/Variable level
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
adata.obs

        cell_type
Cell_0          T
Cell_1          B
Cell_2          B
Cell_3   Monocyte
Cell_4          T
...           ...
Cell_95         T
Cell_96  Monocyte
Cell_97         T
Cell_98  Monocyte
Cell_99  Monocyte

[100 rows x 1 columns]

In [ ]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'

In [ ]:
# subsetting using metadata
bdata = adata[adata.obs.cell_type == "B"]
bdata

View of AnnData object with n_obs × n_vars = 31 × 2000
    obs: 'cell_type'

In [ ]:
# Observation/variable-level matrices
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))
adata.obsm

AxisArrays with keys: X_umap

In [ ]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    obsm: 'X_umap'
    varm: 'gene_stuff'

In [ ]:
# unstructured metadata
adata.uns["random"] = [1, 2, 3]
adata.uns

OrderedDict([('random', [1, 2, 3])])

In [ ]:
# layers
adata.layers["log_transformed"] = np.log1p(adata.X)
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    uns: 'random'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

In [ ]:
# conversion to dataframes
adata.to_df(layer="log_transformed")

,Gene_0,Gene_1,Gene_2,Gene_3,Gene_4,Gene_5,Gene_6,Gene_7,Gene_8,Gene_9,...,Gene_1990,Gene_1991,Gene_1992,Gene_1993,Gene_1994,Gene_1995,Gene_1996,Gene_1997,Gene_1998,Gene_1999
Cell_0,0.693147,0.693147,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,1.386294,0.693147,...,0.000000,0.693147,0.693147,1.098612,0.693147,1.609438,1.098612,0.000000,0.693147,1.098612
Cell_1,0.000000,0.000000,0.693147,0.693147,0.000000,1.098612,0.000000,0.693147,0.000000,0.693147,...,0.693147,0.693147,1.098612,0.000000,0.693147,0.000000,0.693147,0.000000,0.693147,0.693147
Cell_2,1.098612,0.000000,0.693147,1.098612,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,...,0.693147,0.000000,0.693147,1.386294,1.098612,0.000000,0.000000,0.693147,0.693147,0.693147
Cell_3,0.000000,0.000000,0.000000,0.000000,0.693147,1.386294,1.098612,0.693147,0.693147,0.693147,...,0.693147,0.000000,0.000000,0.000000,0.693147,0.000000,1.386294,0.693147,0.000000,0.693147
Cell_4,0.000000,0.000000,0.693147,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,1.098612,...,0.000000,0.693147,0.693147,1.098612,1.098612,0.693147,0.000000,1.098612,0.693147,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cell_95,0.693147,0.693147,0.000000,1.098612,0.000000,0.000000,1.098612,0.693147,1.098612,0.000000,...,0.000000,1.098612,0.000000,0.693147,0.693147,0.693147,0.000000,1.098612,0.693147,0.693147
Cell_96,0.693147,0.693147,1.098612,0.693147,0.000000,0.000000,0.000000,1.098612,0.000000,0.000000,...,0.000000,0.000000,0.693147,1.098612,0.693147,0.693147,0.000000,0.693147,0.693147,0.693147
Cell_97,0.693147,0.000000,1.098612,1.386294,0.693147,0.000000,0.000000,0.000000,1.386294,0.000000,...,0.693147,1.098612,0.000000,0.000000,0.693147,0.693147,1.098612,0.693147,0.000000,1.098612
Cell_98,0.000000,0.693147,0.000000,0.000000,1.098612,0.000000,0.693147,0.000000,1.098612,1.098612,...,1.386294,0.693147,0.693147,1.098612,0.000000,0.000000,1.098612,0.000000,0.000000,0.000000
Cell_99,0.000000,0.000000,0.000000,0.000000,1.609438,1.098612,0.000000,0.000000,0.000000,1.609438,...,1.386294,0.000000,0.000000,0.693147,0.000000,1.098612,0.000000,0.693147,0.693147,0.000000

In [ ]:
# views and copies
obs_meta = pd.DataFrame({
        'time_yr': np.random.choice([0, 2, 4, 8], adata.n_obs),
        'subject_id': np.random.choice(['subject 1', 'subject 2', 'subject 4', 'subject 8'], adata.n_obs),
        'instrument_type': np.random.choice(['type a', 'type b'], adata.n_obs),
        'site': np.random.choice(['site x', 'site y'], adata.n_obs),
    },
    index=adata.obs.index,    # these are the same IDs of observations as above!
)

In [ ]:
adata = ad.AnnData(adata.X, obs=obs_meta, var=adata.var)

In [ ]:
print(adata)

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
# access to first 5 rows of two variables
adata[:5, ['Gene_1', 'Gene_3']]

View of AnnData object with n_obs × n_vars = 5 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
# If we want an AnnData that holds the data in memory, let’s call .copy()
adata_subset = adata[:5, ['Gene_1', 'Gene_3']].copy()

In [ ]:
print(adata[:3, 'Gene_1'].X.toarray().tolist())
adata[:3, 'Gene_1'].X = [0, 0, 0]
print(adata[:3, 'Gene_1'].X.toarray().tolist())

[[1.0], [0.0], [0.0]]
[[0.0], [0.0], [0.0]]

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:639: FutureWarning: Setting element `.X` of view of `AnnData` object will obey copy-on-write semantics in the next minor release.
  if self._handle_view_X_cow(value):
/tmp/ipykernel_6674/2822107891.py:2: ImplicitModificationWarning: Modifying `X` on a view results in data being overridden
  adata[:3, 'Gene_1'].X = [0, 0, 0]

In [ ]:
# If you try to access parts of a view of an AnnData, the content will be auto-copied and a data-storing object will be generated
adata_subset = adata[:3, ['Gene_1', 'Gene_2']]

In [ ]:
adata_subset

View of AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
adata_subset.obs['foo'] = range(3)

/tmp/ipykernel_6674/2955902014.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata_subset.obs['foo'] = range(3)

In [ ]:
adata_subset

AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site', 'foo'

In [ ]:
adata[adata.obs.time_yr.isin([2, 4])].obs.head()

         time_yr subject_id instrument_type    site
Cell_1         4  subject 2          type b  site x
Cell_7         2  subject 4          type b  site y
Cell_9         4  subject 8          type b  site y
Cell_11        2  subject 4          type b  site x
Cell_13        2  subject 8          type a  site y

In [ ]:
# partial reading of large data
adata = ad.read_h5ad('my_results.h5ad', backed='r')

In [ ]:
adata.isbacked

True

In [ ]:
adata.filename

PosixPath('my_results.h5ad')

In [ ]:
adata.file.close()